#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Switch the active Fabric workspace and write resource IDs to .env.

Reads from workspaces.json (populated by tool/workspace/init.py). Does not
call the Fabric API — all data is already in the registry.

After switching, the MCP server must be restarted to pick up the new .env
values (it reads .env only at startup).

Usage:
    python tool/workspace/switch.py list
    python tool/workspace/switch.py <displayName>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path.cwd()
REGISTRY = ROOT / "workspaces.json"
ENV_FILE = ROOT / ".env"

_AUTO_BEGIN = "# --- auto-generated by switch.py — do not edit below this line ---"
_AUTO_END = "# --- end auto-generated ---"


def _env_name(display_name: str) -> str:
    return display_name.upper().replace(" ", "_").replace("-", "_")


def _load_registry() -> dict:
    if not REGISTRY.exists():
        raise SystemExit(
            "workspaces.json not found.\n"
            "Run: python tool/workspace/init.py"
        )
    try:
        return json.loads(REGISTRY.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"workspaces.json is malformed: {exc}") from exc


def _find_workspace(registry: dict, name: str) -> dict:
    for ws in registry.get("workspaces", []):
        if ws.get("displayName", "").lower() == name.lower():
            return ws
    names = [ws.get("displayName", "") for ws in registry.get("workspaces", [])]
    raise SystemExit(
        f"Workspace not found: {name!r}\n"
        f"Available: {', '.join(names) or '(none)'}\n"
        "Run: python tool/workspace/init.py  (to refresh the registry)"
    )


def _read_env_credentials() -> str:
    """Return the credentials portion of .env (everything before the auto-generated block)."""
    if not ENV_FILE.exists():
        return ""
    text = ENV_FILE.read_text(encoding="utf-8")
    if _AUTO_BEGIN in text:
        return text[: text.index(_AUTO_BEGIN)].rstrip("\n")
    return text.rstrip("\n")


def cmd_list(registry: dict) -> None:
    workspaces = registry.get("workspaces", [])
    active = registry.get("active")
    refreshed = registry.get("refreshed_at", "unknown")
    if not workspaces:
        print("No workspaces discovered. Run: python tool/workspace/init.py")
        return
    print(f"Workspace registry  (refreshed: {refreshed})")
    print()
    for ws in workspaces:
        marker = "* " if ws.get("displayName") == active else "  "
        lh_names = [i.get("displayName", "") for i in ws.get("items", {}).get("Lakehouse", [])]
        wh_names = [i.get("displayName", "") for i in ws.get("items", {}).get("Warehouse", [])]
        nb_count = len(ws.get("items", {}).get("Notebook", []))
        pl_count = len(ws.get("items", {}).get("DataPipeline", []))
        print(f"{marker}{ws.get('displayName')}  [{ws.get('id', '')}]")
        print(f"    Lakehouses:  {', '.join(lh_names) or '—'}")
        print(f"    Warehouses:  {', '.join(wh_names) or '—'}")
        print(f"    Notebooks: {nb_count}   DataPipelines: {pl_count}")
        print()


def cmd_switch(registry: dict, name: str) -> None:
    ws = _find_workspace(registry, name)
    ws_id = ws.get("id", "")
    ws_name = ws.get("displayName", name)

    lines = [_AUTO_BEGIN]
    lines.append(f"FABRIC_WORKSPACE_ID={ws_id}")

    for lh in ws.get("items", {}).get("Lakehouse", []):
        lh_name = lh.get("displayName", "")
        lh_id = lh.get("id", "")
        lines.append(f"FABRIC_LAKEHOUSE_{_env_name(lh_name)}={lh_id}")

    for wh in ws.get("items", {}).get("Warehouse", []):
        wh_name = wh.get("displayName", "")
        wh_id = wh.get("id", "")
        conn_str = (wh.get("properties") or {}).get("connectionString", "")
        lines.append(f"FABRIC_WAREHOUSE_{_env_name(wh_name)}={wh_id}")
        if conn_str:
            lines.append(f"FABRIC_WAREHOUSE_HOST={conn_str}")

    lines.append(_AUTO_END)
    auto_block = "\n".join(lines)

    creds = _read_env_credentials()
    new_env = (creds + "\n\n" + auto_block + "\n") if creds else (auto_block + "\n")
    ENV_FILE.write_text(new_env, encoding="utf-8")

    registry["active"] = ws_name
    REGISTRY.write_text(json.dumps(registry, indent=2), encoding="utf-8")

    lh_names = [i.get("displayName", "") for i in ws.get("items", {}).get("Lakehouse", [])]
    wh_names = [i.get("displayName", "") for i in ws.get("items", {}).get("Warehouse", [])]
    print(f"Switched to {ws_name}  (id: {ws_id})")
    print(f"  Lakehouses: {', '.join(lh_names) or '—'}")
    print(f"  Warehouses: {', '.join(wh_names) or '—'}")
    print()
    print("Reload your Claude Code session — the MCP server reads .env only at startup.")


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        raise SystemExit(1)

    registry = _load_registry()
    command = sys.argv[1]

    if command == "list":
        cmd_list(registry)
    else:
        cmd_switch(registry, " ".join(sys.argv[1:]))


if __name__ == "__main__":
    main()
